export {default as Login} from './Login' 
export {default as Register} from './Register' 
export {default as Profile} from './Profile' 
export {default as Chat} from './Chat' 
export {default as UsersList} from './UsersList' 
export {default as UploadDocs} from './UploadDocs' 
